In [1]:
import pandas as pd
pd.set_option('display.max_columns',None)

In [2]:
horse_pred = pd.read_csv("races.csv")
horse_pred.head()

,race_id,date,venue,race_no,config,surface,distance,going,horse_ratings,prize,race_class,sec_time1,sec_time2,sec_time3,sec_time4,sec_time5,sec_time6,sec_time7,time1,time2,time3,time4,time5,time6,time7,place_combination1,place_combination2,place_combination3,place_combination4,place_dividend1,place_dividend2,place_dividend3,place_dividend4,win_combination1,win_dividend1,win_combination2,win_dividend2
0,0,1997-06-02,ST,1,A,0,1400,GOOD TO FIRM,40-15,485000.0,5,13.53,21.59,23.94,23.58,NaN,NaN,NaN,13.53,35.12,59.06,82.64,NaN,NaN,NaN,8,11,6.0,NaN,36.5,25.5,18.0,NaN,8,121.0,NaN,NaN
1,1,1997-06-02,ST,2,A,0,1200,GOOD TO FIRM,40-15,485000.0,5,24.05,22.64,23.70,NaN,NaN,NaN,NaN,24.05,46.69,70.39,NaN,NaN,NaN,NaN,5,13,4.0,NaN,12.5,47.0,33.5,NaN,5,23.5,NaN,NaN
2,2,1997-06-02,ST,3,A,0,1400,GOOD TO FIRM,60-40,625000.0,4,13.77,22.22,24.88,22.82,NaN,NaN,NaN,13.77,35.99,60.87,83.69,NaN,NaN,NaN,11,1,13.0,NaN,23.0,23.0,59.5,NaN,11,70.0,NaN,NaN
3,3,1997-06-02,ST,4,A,0,1200,GOOD TO FIRM,120-95,1750000.0,1,24.33,22.47,22.09,NaN,NaN,NaN,NaN,24.33,46.80,68.89,NaN,NaN,NaN,NaN,5,3,10.0,NaN,14.0,24.5,16.0,NaN,5,52.0,NaN,NaN
4,4,1997-06-02,ST,5,A,0,1600,GOOD TO FIRM,60-40,625000.0,4,25.45,23.52,23.31,23.56,NaN,NaN,NaN,25.45,48.97,72.28,95.84,NaN,NaN,NaN,2,10,1.0,NaN,15.5,28.0,17.5,NaN,2,36.5,NaN,NaN

In [3]:
horse_pred.head()

,race_id,date,venue,race_no,config,surface,distance,going,horse_ratings,prize,race_class,sec_time1,sec_time2,sec_time3,sec_time4,sec_time5,sec_time6,sec_time7,time1,time2,time3,time4,time5,time6,time7,place_combination1,place_combination2,place_combination3,place_combination4,place_dividend1,place_dividend2,place_dividend3,place_dividend4,win_combination1,win_dividend1,win_combination2,win_dividend2
0,0,1997-06-02,ST,1,A,0,1400,GOOD TO FIRM,40-15,485000.0,5,13.53,21.59,23.94,23.58,NaN,NaN,NaN,13.53,35.12,59.06,82.64,NaN,NaN,NaN,8,11,6.0,NaN,36.5,25.5,18.0,NaN,8,121.0,NaN,NaN
1,1,1997-06-02,ST,2,A,0,1200,GOOD TO FIRM,40-15,485000.0,5,24.05,22.64,23.70,NaN,NaN,NaN,NaN,24.05,46.69,70.39,NaN,NaN,NaN,NaN,5,13,4.0,NaN,12.5,47.0,33.5,NaN,5,23.5,NaN,NaN
2,2,1997-06-02,ST,3,A,0,1400,GOOD TO FIRM,60-40,625000.0,4,13.77,22.22,24.88,22.82,NaN,NaN,NaN,13.77,35.99,60.87,83.69,NaN,NaN,NaN,11,1,13.0,NaN,23.0,23.0,59.5,NaN,11,70.0,NaN,NaN
3,3,1997-06-02,ST,4,A,0,1200,GOOD TO FIRM,120-95,1750000.0,1,24.33,22.47,22.09,NaN,NaN,NaN,NaN,24.33,46.80,68.89,NaN,NaN,NaN,NaN,5,3,10.0,NaN,14.0,24.5,16.0,NaN,5,52.0,NaN,NaN
4,4,1997-06-02,ST,5,A,0,1600,GOOD TO FIRM,60-40,625000.0,4,25.45,23.52,23.31,23.56,NaN,NaN,NaN,25.45,48.97,72.28,95.84,NaN,NaN,NaN,2,10,1.0,NaN,15.5,28.0,17.5,NaN,2,36.5,NaN,NaN

In [4]:
horse_pred.describe()

,race_id,race_no,surface,distance,prize,race_class,sec_time1,sec_time2,sec_time3,sec_time4,sec_time5,sec_time6,sec_time7,time1,time2,time3,time4,time5,time6,time7,place_combination1,place_combination2,place_combination3,place_combination4,place_dividend1,place_dividend2,place_dividend3,place_dividend4,win_combination1,win_dividend1,win_combination2,win_dividend2
count,6349.000000,6349.000000,6349.000000,6349.000000,5.887000e+03,6349.000000,6349.000000,6349.000000,6349.000000,3634.000000,821.000000,115.000000,0.0,6349.000000,6349.000000,6349.000000,3634.000000,821.000000,115.000000,0.0,6349.00000,6349.000000,6324.000000,23.000000,6349.000000,6349.000000,6324.000000,23.000000,6349.000000,6349.000000,12.000000,12.000000
mean,3174.000000,5.226807,0.109151,1419.113246,1.134790e+06,3.893684,20.699466,22.826749,23.830743,23.852854,23.868685,23.912261,NaN,20.699466,43.526215,67.356959,91.735793,112.479695,140.349739,NaN,6.23862,6.366357,6.525933,8.434783,27.778469,32.802536,38.969292,22.013043,6.238620,96.096944,8.166667,101.416667
std,1832.942761,2.795019,0.311853,281.468745,1.749156e+06,1.992868,5.880319,1.044998,0.870355,0.820277,0.758860,0.667664,NaN,5.880319,6.657225,6.978638,7.814997,5.452576,4.910272,NaN,3.61858,3.662594,3.731685,2.982160,25.175925,30.275423,37.015938,16.757802,3.620321,131.221259,3.325749,101.672566
min,0.000000,1.000000,0.000000,1000.000000,4.850000e+05,0.000000,12.390000,20.060000,21.200000,21.400000,21.810000,21.770000,NaN,12.390000,33.110000,55.160000,80.430000,105.830000,132.840000,NaN,1.00000,1.000000,1.000000,4.000000,10.100000,10.100000,10.100000,10.100000,1.000000,10.500000,3.000000,12.000000
25%,1587.000000,3.000000,0.000000,1200.000000,6.750000e+05,3.000000,13.690000,22.140000,23.210000,23.300000,23.410000,23.550000,NaN,13.690000,35.950000,59.830000,83.410000,109.010000,137.290000,NaN,3.00000,3.000000,3.000000,6.500000,15.000000,17.000000,18.500000,10.100000,3.000000,34.500000,5.500000,25.250000
50%,3174.000000,5.000000,0.000000,1400.000000,8.400000e+05,4.000000,23.720000,22.800000,23.720000,23.770000,23.830000,24.020000,NaN,23.720000,46.410000,69.720000,94.300000,110.330000,138.360000,NaN,6.00000,6.000000,6.000000,8.000000,20.000000,24.000000,27.500000,15.500000,6.000000,58.500000,8.000000,50.250000
75%,4761.000000,7.000000,0.000000,1650.000000,1.060000e+06,4.000000,24.700000,23.450000,24.380000,24.330000,24.280000,24.295000,NaN,24.700000,48.070000,72.100000,100.030000,113.150000,140.205000,NaN,9.00000,9.000000,10.000000,11.000000,31.000000,36.500000,44.000000,24.750000,9.000000,105.500000,11.250000,178.625000
max,6348.000000,11.000000,1.000000,2400.000000,2.500000e+07,13.000000,30.030000,27.410000,27.580000,28.920000,26.500000,25.920000,NaN,30.030000,56.220000,81.290000,107.810000,134.310000,158.490000,NaN,14.00000,14.000000,14.000000,14.000000,410.500000,627.000000,420.500000,68.000000,14.000000,2687.500000,12.000000,282.500000

In [5]:
horse_pred.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6349 entries, 0 to 6348
Data columns (total 37 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   race_id             6349 non-null   int64
 1   date                6349 non-null   object
 2   venue               6349 non-null   object
 3   race_no             6349 non-null   int64
 4   config              6349 non-null   object
 5   surface             6349 non-null   int64
 6   distance            6349 non-null   int64
 7   going               6349 non-null   object
 8   horse_ratings       6349 non-null   object
 9   prize               5887 non-null   float64
 10  race_class          6349 non-null   int64
 11  sec_time1           6349 non-null   float64
 12  sec_time2           6349 non-null   float64
 13  sec_time3           6349 non-null   float64
 14  sec_time4           3634 non-null   float64
 15  sec_time5           821 non-null    float64
 16  sec_time6           115 non-null    float64
 17  sec_time7           0 non-null      float64
 18  time1               6349 non-null   float64
 19  time2               6349 non-null   float64
 20  time3               6349 non-null   float64
 21  time4               3634 non-null   float64
 22  time5               821 non-null    float64
 23  time6               115 non-null    float64
 24  time7               0 non-null      float64
 25  place_combination1  6349 non-null   int64
 26  place_combination2  6349 non-null   int64
 27  place_combination3  6324 non-null   float64
 28  place_combination4  23 non-null     float64
 29  place_dividend1     6349 non-null   float64
 30  place_dividend2     6349 non-null   float64
 31  place_dividend3     6324 non-null   float64
 32  place_dividend4     23 non-null     float64
 33  win_combination1    6349 non-null   int64
 34  win_dividend1       6349 non-null   float64
 35  win_combination2    12 non-null     float64
 36  win_dividend2       12 non-null     float64
dtypes: float64(24), int64(8), object(5)
memory usage: 1.8+ MB

In [6]:
missing = (horse_pred.isnull().sum() / len(horse_pred)) * 100
missing.sort_values(ascending=False)

time7                 100.000000
sec_time7             100.000000
win_dividend2          99.810994
win_combination2       99.810994
place_dividend4        99.637738
place_combination4     99.637738
sec_time6              98.188691
time6                  98.188691
sec_time5              87.068830
time5                  87.068830
time4                  42.762640
sec_time4              42.762640
prize                   7.276736
place_dividend3         0.393763
place_combination3      0.393763
place_dividend2         0.000000
place_dividend1         0.000000
place_combination2      0.000000
place_combination1      0.000000
win_combination1        0.000000
win_dividend1           0.000000
race_id                 0.000000
time3                   0.000000
time2                   0.000000
date                    0.000000
sec_time3               0.000000
sec_time2               0.000000
sec_time1               0.000000
race_class              0.000000
horse_ratings           0.000000
going                   0.000000
distance                0.000000
surface                 0.000000
config                  0.000000
race_no                 0.000000
venue                   0.000000
time1                   0.000000
dtype: float64

In [7]:
drop_cols = ['race_id','time7','sec_time7','win_dividend2','win_combination2','place_dividend4','place_combination4','sec_time6','time6']
horse_pred = horse_pred.drop(drop_cols,axis=1)

In [8]:
horse_pred['prize'].fillna(0,inplace=True)
horse_pred['sec_time4'].fillna(horse_pred['sec_time4'].median(),inplace=True)
horse_pred['sec_time5'].fillna(horse_pred['sec_time5'].median(),inplace=True)
horse_pred['time4'].fillna(horse_pred['time4'].median(),inplace=True)
horse_pred['time5'].fillna(horse_pred['time5'].median(),inplace=True)
horse_pred['place_combination3'].fillna(0,inplace=True)
horse_pred['place_dividend3'].fillna(0,inplace=True)

C:\Users\Dell\AppData\Local\Temp\ipykernel_16408\2580283514.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  horse_pred['prize'].fillna(0,inplace=True)
C:\Users\Dell\AppData\Local\Temp\ipykernel_16408\2580283514.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  horse_pred['sec_time4'].fillna(horse_pred['sec_time4'].median(),inplace=True)
C:\Users\Dell\AppData\Local\Temp\ipykernel_16408\2580283514.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  horse_pred['sec_time5'].fillna(horse_pred['sec_time5'].median(),inplace=True)
C:\Users\Dell\AppData\Local\Temp\ipykernel_16408\2580283514.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  horse_pred['time4'].fillna(horse_pred['time4'].median(),inplace=True)
C:\Users\Dell\AppData\Local\Temp\ipykernel_16408\2580283514.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  horse_pred['time5'].fillna(horse_pred['time5'].median(),inplace=True)
C:\Users\Dell\AppData\Local\Temp\ipykernel_16408\2580283514.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  horse_pred['place_combination3'].fillna(0,inplace=True)
C:\Users\Dell\AppData\Local\Temp\ipykernel_16408\2580283514.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  horse_pred['place_dividend3'].fillna(0,inplace=True)

In [9]:
horse_pred.head()

,date,venue,race_no,config,surface,distance,going,horse_ratings,prize,race_class,sec_time1,sec_time2,sec_time3,sec_time4,sec_time5,time1,time2,time3,time4,time5,place_combination1,place_combination2,place_combination3,place_dividend1,place_dividend2,place_dividend3,win_combination1,win_dividend1
0,1997-06-02,ST,1,A,0,1400,GOOD TO FIRM,40-15,485000.0,5,13.53,21.59,23.94,23.58,23.83,13.53,35.12,59.06,82.64,110.33,8,11,6.0,36.5,25.5,18.0,8,121.0
1,1997-06-02,ST,2,A,0,1200,GOOD TO FIRM,40-15,485000.0,5,24.05,22.64,23.70,23.77,23.83,24.05,46.69,70.39,94.30,110.33,5,13,4.0,12.5,47.0,33.5,5,23.5
2,1997-06-02,ST,3,A,0,1400,GOOD TO FIRM,60-40,625000.0,4,13.77,22.22,24.88,22.82,23.83,13.77,35.99,60.87,83.69,110.33,11,1,13.0,23.0,23.0,59.5,11,70.0
3,1997-06-02,ST,4,A,0,1200,GOOD TO FIRM,120-95,1750000.0,1,24.33,22.47,22.09,23.77,23.83,24.33,46.80,68.89,94.30,110.33,5,3,10.0,14.0,24.5,16.0,5,52.0
4,1997-06-02,ST,5,A,0,1600,GOOD TO FIRM,60-40,625000.0,4,25.45,23.52,23.31,23.56,23.83,25.45,48.97,72.28,95.84,110.33,2,10,1.0,15.5,28.0,17.5,2,36.5

In [10]:
horse_pred.isnull().sum()

date                  0
venue                 0
race_no               0
config                0
surface               0
distance              0
going                 0
horse_ratings         0
prize                 0
race_class            0
sec_time1             0
sec_time2             0
sec_time3             0
sec_time4             0
sec_time5             0
time1                 0
time2                 0
time3                 0
time4                 0
time5                 0
place_combination1    0
place_combination2    0
place_combination3    0
place_dividend1       0
place_dividend2       0
place_dividend3       0
win_combination1      0
win_dividend1         0
dtype: int64

In [11]:
horse_pred.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6349 entries, 0 to 6348
Data columns (total 28 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   date                6349 non-null   object
 1   venue               6349 non-null   object
 2   race_no             6349 non-null   int64
 3   config              6349 non-null   object
 4   surface             6349 non-null   int64
 5   distance            6349 non-null   int64
 6   going               6349 non-null   object
 7   horse_ratings       6349 non-null   object
 8   prize               6349 non-null   float64
 9   race_class          6349 non-null   int64
 10  sec_time1           6349 non-null   float64
 11  sec_time2           6349 non-null   float64
 12  sec_time3           6349 non-null   float64
 13  sec_time4           6349 non-null   float64
 14  sec_time5           6349 non-null   float64
 15  time1               6349 non-null   float64
 16  time2               6349 non-null   float64
 17  time3               6349 non-null   float64
 18  time4               6349 non-null   float64
 19  time5               6349 non-null   float64
 20  place_combination1  6349 non-null   int64
 21  place_combination2  6349 non-null   int64
 22  place_combination3  6349 non-null   float64
 23  place_dividend1     6349 non-null   float64
 24  place_dividend2     6349 non-null   float64
 25  place_dividend3     6349 non-null   float64
 26  win_combination1    6349 non-null   int64
 27  win_dividend1       6349 non-null   float64
dtypes: float64(16), int64(7), object(5)
memory usage: 1.4+ MB

In [12]:
horse_pred = horse_pred.drop(['date','sec_time1','time2','time3','time4','time5','sec_time2', 'sec_time3', 'sec_time4', 'sec_time5','place_combination1','place_combination2','place_combination3','place_dividend1','place_dividend2','place_dividend3','win_combination1','win_dividend1'], axis=1)

In [13]:
horse_pred = pd.get_dummies(horse_pred,drop_first=True)

In [14]:
horse_pred.head()

,race_no,surface,distance,prize,race_class,time1,venue_ST,config_A+3,config_B,config_B+2,config_C,config_C+3,going_GOOD,going_GOOD TO FIRM,going_GOOD TO YIELDING,going_SLOW,going_SOFT,going_WET FAST,going_WET SLOW,going_YIELDING,going_YIELDING TO SOFT,horse_ratings_100-75,horse_ratings_100-80,horse_ratings_105-80,horse_ratings_105-85,horse_ratings_110-80,horse_ratings_110-85,horse_ratings_110-90,horse_ratings_115-90,horse_ratings_115-95,horse_ratings_120-100,horse_ratings_120-95,horse_ratings_40-0,horse_ratings_40-10,horse_ratings_40-15,horse_ratings_40-20,horse_ratings_60-35,horse_ratings_60-40,horse_ratings_65-40,horse_ratings_75-55,horse_ratings_80+,horse_ratings_80-55,horse_ratings_80-60,horse_ratings_85+,horse_ratings_85-60,horse_ratings_90+,horse_ratings_90-70,horse_ratings_95+,horse_ratings_95-70,horse_ratings_95-75,horse_ratings_G
0,1,0,1400,485000.0,5,13.53,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,2,0,1200,485000.0,5,24.05,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,3,0,1400,625000.0,4,13.77,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False
3,4,0,1200,1750000.0,1,24.33,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,5,0,1600,625000.0,4,25.45,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False

In [15]:
from sklearn.model_selection import train_test_split

X = horse_pred.drop('time1',axis=1)
y = horse_pred['time1']

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [16]:
y.shape

(6349,)

In [17]:
from sklearn.linear_model import LinearRegression
lin_model = LinearRegression()
lin_model.fit(X_train, y_train)
y_linear = lin_model.predict(X_test)

In [18]:
from sklearn.tree import DecisionTreeRegressor
tree_model = DecisionTreeRegressor()
tree_model.fit(X_train,y_train)
y_tree = tree_model.predict(X_test)

In [28]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
print("MAE Linear",mean_absolute_error(y_test,y_linear))
print("MAE tree",mean_absolute_error(y_test,y_tree))
print("MSE Linear",mean_squared_error(y_test,y_linear))
print("MSE tree",mean_squared_error(y_test,y_tree))
print("R2 Linear",r2_score(y_test,y_linear))
print("R2 tree",r2_score(y_test,y_tree))
print("R2 Forest",r2_score(y_test,y_forest))

MAE Linear 4.748731499613276
MAE tree 0.300375515560555
MSE Linear 28.33304605945
MSE tree 0.24898141892977663
R2 Linear 0.16464029017648607
R2 tree 0.992659135716216
R2 Forest 0.9952652472741783

In [26]:
from sklearn.ensemble import RandomForestRegressor
forest_model = RandomForestRegressor()
forest_model.fit(X_train,y_train)
y_forest = forest_model.predict(X_test)